backend/course-manager-microservice/src/main/java/edu/oswego/cs/daos/CourseDAO.java
backend/course-manager-microservice/src/main/java/edu/oswego/cs/resources/CourseManager.java
backend/course-manager-microservice/src/main/java/edu/oswego/cs/rest/RestApplication.java
backend/course-manager-microservice/src/main/liberty/config/server.xml

Change Log For PR:
+ Updated CourseDAO for Lombok annotation support
+ Fixed bugs url not rooting to correct endpoint 
+ Updated Server Configuration in server.xml

Read Change Log

---

backend/course-manager-microservice/src/main/java/edu/oswego/cs/database/DatabaseManager.java
backend/course-viewer-microservice/src/main/java/edu/oswego/cs/database/DatabaseManager.java

I swapped the port numbers for the databases, my b

Database networking

---

frontend/src/main/frontend/src/pages/EditCoursePage.js
frontend/src/main/frontend/src/pages/styles/EditCourseStyle.css

Styled editCourse page more inline with what usability is doing on figma.

Updated editCourse CSS

---

backend/course-manager-microservice/src/main/java/edu/oswego/cs/resources/CourseManagerResource.java
backend/course-viewer-microservice/src/main/java/edu/oswego/cs/resources/CoursesViewerResources.java
backend/professor-assignment-microservice/src/main/java/edu/oswego/cs/rest/application/ProfessorAssignmentApplication.java
backend/professor-assignment-microservice/src/main/java/edu/oswego/cs/rest/daos/FileDAO.java
backend/professor-assignment-microservice/src/main/liberty/config/server.xml

Course Manager MS:
- Updated CSV file error response message
Course Viewer MS:
- Individual course information specified in a RESTful request
Professor Assignment MS:
- Updated relative path prefix for navigation out of the maven target directory

Change Log

---

frontend/src/main/frontend/src/components/SubmittedComponent.js
frontend/src/main/frontend/src/components/ToDoComponent.js
frontend/src/main/frontend/src/components/styles/StudentAss.css
frontend/src/main/frontend/src/pages/StudentPages/StudentDashboardPage.js

Added to do and submitted assignments for the classes - dummies for now

Added to do and submitted assignments for the classes - dummies for now

---

backend/course-viewer-microservice/src/main/java/edu/oswego/cs/database/CourseInterface.java
backend/course-viewer-microservice/src/main/java/edu/oswego/cs/resources/CoursesViewerResources.java
backend/professor-assignment-microservice/src/main/java/edu/oswego/cs/rest/database/AssignmentInterface.java
backend/professor-assignment-microservice/src/main/java/edu/oswego/cs/rest/resources/ProfessorAssignmentResource.java
backend/student-assignment-microservice/src/main/java/edu/oswego/cs/rest/database/AssignmentInterface.java
nginx.conf

- Last minute improvements on the algorithms since the previous ones apparently caused some kind of unknown bottleneck/congestion for the database.

Improved algorithm & nginx configuration

---

backend/student-peer-review-assignment-microservice/src/main/java/edu/oswego/cs/daos/FileDAO.java
backend/student-peer-review-assignment-microservice/src/main/java/edu/oswego/cs/database/PeerReviewAssignmentInterface.java
backend/student-peer-review-assignment-microservice/src/main/java/edu/oswego/cs/resources/PeerReviewAssignmentResource.java

file naming scheme is what BT uses in CSC 436 
for-{teamName}/

Distribution + Zip files for distributed assignments

---

backend/professor-assignment-microservice/src/main/java/edu/oswego/cs/rest/database/AssignmentInterface.java

the error would say course not found every time an assignment creation was attempted. and assignment id would duplicate sometimes. 
-fixed

fixed error on create course, added Logans method for unique ID

---

frontend/src/main/frontend/src/components/ProfessorComponents/AssignmentPage/TeacherFinalGradeComponent.js
frontend/src/main/frontend/src/components/styles/FinalGrade.css
frontend/src/main/frontend/src/routing/RouterHandler.js

Updated teacher final grade component, updated css to match student version of the page, added route to handler

Updated Teacher final grade component

---

backend/student-assignment-microservice/src/main/java/edu/oswego/cs/rest/database/AssignmentInterface.java
backend/student-assignment-microservice/src/main/java/edu/oswego/cs/rest/resources/studentAssignmentResource.java

beep boop don't take the loot,
sit in shade don't drink the Kool-aid

added endpoint to return only unsubmitted assignments

---

backend/professor-assignment-microservice/src/main/java/edu/oswego/cs/rest/resources/ProfessorAssignmentResource.java

Added docx as supported file type upload for professor role

---

backend/student-peer-review-assignment-microservice/src/main/java/edu/oswego/cs/database/PeerReviewAssignmentInterface.java
backend/student-peer-review-assignment-microservice/src/main/java/edu/oswego/cs/resources/PeerReviewAssignmentResource.java

when all teams have reviewed a particular submission, said submission will automatically have its grade averaged
fixed typo in makeFinalGrade()
fixed logic error for calculating the final grade

finalize grades completed

---

backend/login-microservice/src/main/java/edu/oswego/cs/database/ProfessorCheck.java
backend/login-microservice/src/main/java/edu/oswego/cs/services/AuthServices.java

To be more in line with the rest of the code base.

Updated professor check initialization flow

---

backend/professor-assignment-microservice/src/main/java/edu/oswego/cs/rest/database/AssignmentInterface.java

- If no assignment is found, return an empty collection instead of throwing 400 bad request.

View assignment endpoint return type fix

---

backend/course-manager-microservice/src/main/java/edu/oswego/cs/database/CourseInterface.java
backend/course-manager-microservice/src/main/java/edu/oswego/cs/resources/CourseManagerResource.java

Updated return value in updateCourse API to fix issue #265 -- broken url

Fixing #265

---

backend/course-manager-microservice/src/main/java/edu/oswego/cs/database/DatabaseManager.java
backend/course-viewer-microservice/src/main/java/edu/oswego/cs/database/DatabaseManager.java
backend/login-microservice/src/main/java/edu/oswego/cs/database/DatabaseManager.java
backend/peer-review-teams-microservice/src/main/java/edu/oswego/cs/database/DatabaseManager.java
backend/professor-assignment-microservice/src/main/java/edu/oswego/cs/rest/database/DatabaseManager.java
backend/student-assignment-microservice/src/main/java/edu/oswego/cs/rest/database/DatabaseManager.java
backend/student-peer-review-assignment-microservice/src/main/java/edu/oswego/cs/database/DatabaseManager.java
docker-compose.yml
env.example

- Significantly simplified setup for both development and production environment where `docker-compose.yml` uses environment variables instead of having to update in multiple places.
- #288 fix: No longer exposes database ports to host machine due to security concerns. Database operations should now work with each other locally on the server and no longer sending direct requests via host address.

Reworked and simplified database connection

---

frontend/src/main/frontend/package.json
frontend/src/main/frontend/src/index.js
frontend/src/main/frontend/src/pages/AuthPages/LoginPage.js
frontend/src/main/frontend/yarn.lock

Reverts tenbergen/CSC480-22S#306
auth issues cannot be fixed until https is used in the public domain

Revert "auth issues fixed on frontend"

---

.gitignore
backend/course-manager-microservice/src/main/java/edu/oswego/cs/database/CourseInterface.java
backend/login-microservice/src/main/java/edu/oswego/cs/services/AuthServices.java
backend/peer-review-teams-microservice/src/main/java/edu/oswego/cs/database/TeamInterface.java
backend/peer-review-teams-microservice/src/main/java/edu/oswego/cs/services/IdentifyingService.java
backend/professor-assignment-microservice/pom.xml
backend/professor-assignment-microservice/src/main/java/edu/oswego/cs/rest/daos/AssignmentDAO.java
backend/professor-assignment-microservice/src/main/java/edu/oswego/cs/rest/database/AssignmentInterface.java
backend/professor-assignment-microservice/src/main/java/edu/oswego/cs/rest/resources/ProfessorAssignmentResource.java
backend/professor-assignment-microservice/src/test/java/ProfessorAssignmentTests.java
backend/student-assignment-microservice/src/main/java/edu/oswego/cs/rest/daos/FileDAO.java
backend/student-assignment-microservice/src/main/java/edu/oswego/cs/rest/database/AssignmentInterface.java
frontend/src/main/frontend/src/components/ProfessorComponents/CoursesPage/ProfessorRosterComponent.js

- Fixed issue with content filter where every thing was said to have profanity even when it did not.
- Fixed issue where professors who are students in another class could not access any of the course materials
- Fixed merge issue in professor roster component

Various engine fixes

---

backend/professor-assignment-microservice/src/main/java/edu/oswego/cs/rest/resources/ProfessorAssignmentResource.java
backend/professor-assignment-microservice/src/main/liberty/config/server.xml
backend/student-assignment-microservice/src/main/java/edu/oswego/cs/rest/daos/FileDAO.java
frontend/src/main/frontend/src/components/StudentComponents/AssignmentPage/RegularAssignmentComponent.js
frontend/src/main/frontend/src/components/StudentComponents/AssignmentPage/StudentPeerReviewComponent.js

Had a minor error in the backend with detecting profanity that has now been fixed

Profanity Filter fix

---

.circleci/config.yml

Update CircleCi yml file Version 1.9

Update CircleCi Yml file Version 1.9

---

backend/course-manager-microservice/course-manager-microservice.iml
backend/course-viewer-microservice/course-viewer-microservice.iml
backend/login-microservice/login-microservice.iml
backend/peer-review-teams-microservice/peer-review-teams-microservice.iml
backend/peer-review-teams-microservice/src/main/java/edu/oswego/cs/database/TeamInterface.java
backend/professor-assignment-microservice/professor-assignment-microservice.iml
backend/student-assignment-microservice/src/main/java/edu/oswego/cs/rest/database/AssignmentInterface.java
backend/student-assignment-microservice/src/main/java/edu/oswego/cs/rest/resources/studentAssignmentResource.java
backend/student-assignment-microservice/student-assignment-microservice.iml
backend/student-peer-review-assignment-microservice/student-peer-review-assignment-microservice.iml
frontend/Frontend.iml

Fixed issue where a team would be created and the team id would not be added to the student object. This also fixes a bug I found with the bulk downloads for a specific student where it would not add the peer reviews that the student's team made

Fixed Team Creation Issue

---

nginx.conf
nginxDBandProxy.conf
nginxfrontend.conf
nginxlocal.conf

Contains a fix for the nginx config preventing people from accessing the login page

Fixed nginx config

---

discord/src/commands/eval.js
discord/src/commands/index.js
discord/src/events/ready.js

Added an eval command for debugging purposes

Added eval command

---

frontend/src/main/frontend/src/pages/StudentPages/StudentGradesPage.js
frontend/src/main/frontend/src/pages/StudentPages/styles/StudentGradesStyling.css
frontend/src/main/frontend/src/routing/RouterHandler.js

Added the frontend code for the student grades overview page

Student Grades Overview Page

---

backend/course-manager-microservice/pom.xml
backend/course-manager-microservice/src/main/java/edu/oswego/cs/daos/CourseDAO.java
backend/course-manager-microservice/src/main/java/edu/oswego/cs/database/CourseInterface.java
backend/course-manager-microservice/src/main/java/edu/oswego/cs/resources/CourseManagerResource.java

PR for Instructor Blocked words endpoint.

Instructor blocked words

---

backend/course-manager-microservice/src/main/java/edu/oswego/cs/database/CourseInterface.java
backend/student-assignment-microservice/src/main/java/edu/oswego/cs/rest/resources/studentAssignmentResource.java
backend/student-peer-review-assignment-microservice/src/main/java/edu/oswego/cs/database/PeerReviewAssignmentInterface.java
frontend/src/main/frontend/src/components/AssignmentDropdown.js
frontend/src/main/frontend/src/components/styles/AssignmentDropdown.module.css
frontend/src/main/frontend/src/pages/TeacherPages/DisplayMatrix.js
frontend/src/main/frontend/src/pages/TeacherPages/styles/DisplayMatrix.module.css
frontend/src/main/frontend/src/routing/RouterHandler.js

Should be the complete, stripped code changes from JamesL original PR

JamesL updates from PR 445, originally from for jal1999:Engine

---

.gitignore
frontend/src/main/frontend/src/components/Breadcrumbs.js
frontend/src/main/frontend/src/components/HeaderBar/HeaderBar.js
frontend/src/main/frontend/src/components/ProfessorComponents/AssignmentPage/ProfessorEditAssignmentComponent.js
frontend/src/main/frontend/src/components/ProfessorComponents/CoursesPage/ProfessorEditCourseComponent.js
frontend/src/main/frontend/src/components/ProfessorComponents/CoursesPage/ProfessorProfanitySettingsComponent.js
frontend/src/main/frontend/src/components/ProfessorComponents/CoursesPage/ProfessorTeamComponent.js
frontend/src/main/frontend/src/components/styles/EditCourse.css
frontend/src/main/frontend/src/pages/TeacherPages/ProfessorCoursePage.js
frontend/src/main/frontend/src/routing/RouterHandler.js

Added profanity page for professor that just needs to be hooked up to the backend and aesthetic improvements throughout

GUI Professor Profanity Page

---

frontend/src/main/frontend/src/routing/RouterHandler.js

Reverts tenbergen/CSC480-22S#493

Revert "G UI"

---

frontend/src/main/frontend/src/components/StudentComponents/PeerReviewPage/PeerReviewListPage.js
frontend/src/main/frontend/src/components/StudentComponents/PeerReviewPage/styles/PeerReviewListStyle.css

Modal Implementation with button functionality and styling

Student assignment

---

backend/student-peer-review-assignment-microservice/src/main/java/edu/oswego/cs/database/PeerReviewAssignmentInterface.java
frontend/src/main/frontend/src/components/ProfessorComponents/AssignmentPage/ProfessorAllSubmissionsComponent.js
frontend/src/main/frontend/src/components/StudentComponents/PeerReviewPage/styles/PeerReviewListStyle.css
frontend/src/main/frontend/src/components/styles/Roster.css

Fized issue where the grade_finalized value would remain false in the assignment document even when all the peer reviews had been submitted.

Grade_finalized value error fixed

---

frontend/src/main/frontend/src/components/ProfessorComponents/CoursesPage/ProfessorRosterComponent.js
frontend/src/main/frontend/src/components/styles/Roster.module.css

Roster Component according to Figma with button functionality

---

frontend/src/main/frontend/src/pages/TeacherPages/ProfessorSubmittedAssignmentPage.js

page does not build, currently debugging

Instructor pr

---

backend/student-peer-review-assignment-microservice/src/main/java/edu/oswego/cs/database/PeerReviewAssignmentInterface.java
frontend/src/main/frontend/package.json
frontend/src/main/frontend/src/components/AssignmentDropdown.js
frontend/src/main/frontend/src/components/NavigationComponents/CourseAccordionComponent.js
frontend/src/main/frontend/src/components/StudentComponents/AssignmentPage/StudentPeerReviewComponent.js
frontend/src/main/frontend/src/pages/TeacherPages/DisplayMatrix.js
frontend/src/main/frontend/src/pages/TeacherPages/styles/DisplayMatrix.module.css
frontend/src/main/frontend/src/routing/RouterHandler.js
frontend/src/main/frontend/yarn.lock

The display matrix page is now implemented, but there are definitely bugs going on that I don't have enough time to sus out and fix before 5 AM. The styling is now there though and the bugs could be fixed, and that's the only reason I'm doing this PR since the feature is pretty much there as of now.

Display Matrix Page Implemented

---

frontend/src/main/frontend/src/pages/StudentPages/PeerReviewPage.js
frontend/src/main/frontend/src/pages/StudentPages/StudentAssignmentPage.js
frontend/src/main/frontend/src/pages/StudentPages/StudentCoursePage.js
frontend/src/main/frontend/src/pages/StudentPages/StudentSubmittedAssignmentPage.js

Fixed refresh nav bug in student pages.

Deleted empty file PeerReviewGRComponent.js

---

frontend/src/main/frontend/src/pages/TeacherPages/CreateAssignmentPage.js
frontend/src/main/frontend/src/pages/TeacherPages/CreateCoursePage.js
frontend/src/main/frontend/src/pages/TeacherPages/DisplayMatrix.js
frontend/src/main/frontend/src/pages/TeacherPages/ProfessorAssignmentPage.js
frontend/src/main/frontend/src/pages/TeacherPages/ProfessorCoursePage.js
frontend/src/main/frontend/src/pages/TeacherPages/ProfessorGradesPage.js
frontend/src/main/frontend/src/pages/TeacherPages/ProfessorSubmittedAssignmentPage.js

Prof nav refresh bug fix

---

frontend/src/main/frontend/src/components/ProfessorComponents/CoursesPage/ProfessorRosterComponent.js
frontend/src/main/frontend/src/routing/RouterHandler.js

and  also fixed a routing issue I came across on the student peer review page

Fixed issue where the wrong student was being deleted on the professor roster page
